<a href="https://colab.research.google.com/github/devdatta1429/CAPSTONE_EDA/blob/main/Day_11_29_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np
import pandas as pd
# import warnings
# warnings.filterwarnings("ignore")
# pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
import os
print(os.getcwd())
os.chdir('/content/drive/MyDrive/CDAC')
os.getcwd()

/content/drive/My Drive/CDAC

'/content/drive/MyDrive/CDAC'

In [56]:
df = pd.read_csv('ecommerce-transactions-raw.csv')

#
## 🔶Giving over-view of the DataSet🔶

In [57]:
df.head()

,transaction_id,user_id,product_id,product_category,sub_category,product_price,discount_percent,final_price,quantity,transaction_date,payment_mode,order_status,delivery_date,delivery_days,return_flag,return_reason,return_date,seller_rating,customer_rating,buyer_state,seller_state,customer_segment,gst_amount,shipping_cost,refund_amount,device_type,browser_type,session_duration_min,has_reviews,loyalty_member
0,TXN_0000000000,131958,PID_193175,Sports,Team Sports,2998.912641,60,1199.565056,4,2022-08-17,Wallet,Returned,2022-08-20 00:00:00,3.0,1,Size Mismatch,2022-08-30 00:00:00,4.312578,3.708230,KA,MH,Premium,863.686841,0.0,4798.260226,Desktop,Edge,19.334006,1,NaN
1,TXN_0000000001,156867,PID_333865,Electronics,Mobile,5220.659851,70,1566.197955,2,2022-02-21,COD,Cancelled,NaN,NaN,1,Wrong Item,2022-03-02 00:00:00,NaN,NaN,TN,HR,Basic,563.831264,0.0,3132.395911,Mobile,Opera,33.591958,0,Yes
2,TXN_0000000002,141932,PID_837148,Furniture,Lighting,9872.169189,45,5429.693054,3,2023-07-18,Wallet,Completed,NaN,NaN,0,NaN,NaN,3.535101,4.141273,MH,TN,Premium,2932.034249,0.0,NaN,Tablet,Safari,32.615823,0,NaN
3,TXN_0000000003,375838,PID_911087,Books,Self-Help,3144.453832,90,314.445383,1,2023-05-17,COD,Pending,2023-05-24 00:00:00,7.0,0,NaN,NaN,3.999951,4.636294,HR,HR,Basic,15.722269,0.0,NaN,Mobile,Firefox,21.880198,1,NaN
4,TXN_0000000004,269178,PID_728478,Electronics,Smartwatch,727.618316,25,537.578346,1,2023-04-03,UPI,Returned,2023-04-11 00:00:00,8.0,0,NaN,NaN,4.597598,5.000000,TN,UP,Standard,96.764102,0.0,NaN,Tablet,Edge,0.916835,1,NaN

#
## 🔶Giving information of the DataSet🔶

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2030000 entries, 0 to 2029999
Data columns (total 30 columns):
 #   Column                Dtype
---  ------                -----
 0   transaction_id        object
 1   user_id               int64
 2   product_id            object
 3   product_category      object
 4   sub_category          object
 5   product_price         float64
 6   discount_percent      int64
 7   final_price           float64
 8   quantity              int64
 9   transaction_date      object
 10  payment_mode          object
 11  order_status          object
 12  delivery_date         object
 13  delivery_days         float64
 14  return_flag           int64
 15  return_reason         object
 16  return_date           object
 17  seller_rating         float64
 18  customer_rating       float64
 19  buyer_state           object
 20  seller_state          object
 21  customer_segment      object
 22  gst_amount            float64
 23  shipping_cost         float64
 24  refund_amount         float64
 25  device_type           object
 26  browser_type          object
 27  session_duration_min  float64
 28  has_reviews           int64
 29  loyalty_member        object
dtypes: float64(9), int64(5), object(16)
memory usage: 464.6+ MB

#
## 🔶View of nulls, duplicate values of the DataSet🔶

In [59]:
nulls = df.isnull().sum()
duplicated = df.duplicated().sum()
unique = df.nunique()
datatypes = df.dtypes

before_clean = pd.DataFrame({
    'Total Nulls' : nulls,
    'duplicated' : duplicated,
    'unique' : unique,
   'datatypes' : datatypes
})

before_clean

                      Total Nulls  duplicated   unique datatypes
transaction_id                  0       30000  2000000    object
user_id                         0       30000   481901     int64
product_id                      0       30000   802420    object
product_category                0       30000        8    object
sub_category                    0       30000       38    object
product_price                   0       30000  2000000   float64
discount_percent                0       30000       21     int64
final_price                     0       30000  2000000   float64
quantity                        0       30000       11     int64
transaction_date                0       30000     1096    object
payment_mode               338420       30000        5    object
order_status                    0       30000        4    object
delivery_date              405875       30000     1113    object
delivery_days              405875       30000       13   float64
return_flag                     0       30000        2     int64
return_reason             1725017       30000        6    object
return_date               1725017       30000     1123    object
seller_rating              203413       30000  1635588   float64
customer_rating            203413       30000  1621415   float64
buyer_state                     0       30000       13    object
seller_state                    0       30000       13    object
customer_segment                0       30000        3    object
gst_amount                      0       30000  2000000   float64
shipping_cost               20377       30000    10004   float64
refund_amount             1725017       30000   300549   float64
device_type                     0       30000        3    object
browser_type                    0       30000        5    object
session_duration_min            0       30000  2000000   float64
has_reviews                     0       30000        2     int64
loyalty_member             678474       30000        2    object

#
## 🔶Handling null value of return_reason,return_date🔶

In [60]:
before = df[['return_reason' , 'return_date']].isnull().sum().to_frame(name='Missing_Count')
print(before)
print()

df['return_date'] = df['return_date'].fillna('Unknown')
df['return_reason'] = df['return_reason'].fillna('Unknown')

after = df[['return_reason' , 'return_date']].isnull().sum().to_frame(name='Missing_Count')
print(after)
after

               Missing_Count
return_reason        1725017
return_date          1725017

               Missing_Count
return_reason              0
return_date                0

               Missing_Count
return_reason              0
return_date                0

In [61]:
before_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, transaction_id to loyalty_member
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Total Nulls  30 non-null     int64
 1   duplicated   30 non-null     int64
 2   unique       30 non-null     int64
 3   datatypes    30 non-null     object
dtypes: int64(3), object(1)
memory usage: 2.2+ KB